name: CICD
on:
  workflow_dispatch:
    inputs:
      environments:
        description: "This is the environment where workflow runs"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod
          - staging

jobs:
#every job needs seprate runner , its called parallelism
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: echo "Code cloned from GitHub"

  builds:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Container
        run: echo "Docker container build"

  test:
    needs: builds
    runs-on: ubuntu-latest
    steps:
      - name: Test the Container
        run: echo "Testing the container"

  deploy:
    needs: [builds,test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the App
        run: echo "Docker Compose deployed the app"
