---
name: Hello Workflow
on:
  push: null
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Print Hello
        run: echo "Hello World"
  details:
    runs-on: ubuntu-latest
    steps:
      - name: Show Docker and Python Version
        run: docker --version python --version
